### PR TITLE
Fix for Vim 8.1.0365 - 8.1.2054 on Windows

### PR DESCRIPTION
**Pull request by hattya**

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks!
Can you add a test, please? (see 0ab0e74) - or otherwise provide an example line (although I can imagine, it would be good to have it)

**Comment by hattya** [comment]
Here you go.

**Comment by blueyed** [comment]
Awesome, thanks!

**Comment by blueyed** [comment]
Released as 0.2.1.

**Pull request merged**
